# Created by Jekyll Writer
safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
baseurl: /spring-session
name: Spring Session
project: spring-session
github_repo_url: 'http://github.com/spring-projects/spring-session'
custom_pom_template: false
custom_gradle_template: false
main_site_url: 'http://spring.io'
projects_site_url: 'http://projects.spring.io'
questions_url: 'http://spring.io/questions'
